export interface Medicine {
  PRODUCT_TYPE: string;
  PRODUCT_NAME: string;
  PROCESS_FINALIZATION_DATE: string;
  REGULATORY_CATEGORY: string;
  PRODUCT_REGISTRATION_NUMBER: string;
  REGISTRATION_EXPIRATION_DATE: string;
  PROCESS_NUMBER: string;
  THERAPEUTIC_CLASS: string;
  REGISTRATION_HOLDER_COMPANY: string;
  REGISTRATION_STATUS: string;
  ACTIVE_INGREDIENT: string;
}
